name: Run API Tests and Publish Allure

on:
  workflow_dispatch:  

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest allure-pytest

      - name: Run tests with pytest and generate Allure results
        run: |
          pytest tests/ -v --alluredir=allure-results -s

      - name: Generate Allure report
        run: |
          npx allure generate allure-results --clean -o allure-report

      - name: Deploy Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          # Опционально: папка на gh-pages, например "allure"
          # publish_branch: gh-pages
          # destination_dir: allure
