name: Python Tests with Allure

on:
  workflow_dispatch: 
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run Pytest and Generate Allure Report

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install allure-pytest

      - name: Run tests with Allure results
        run: |
          mkdir -p allure-results
          pytest --alluredir=allure-results
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Generate Allure Report
        uses: allure-framework/allure-action@v3
        with:
          results: allure-results
          report: allure-report

      - name: Upload Allure Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

  publish-pages:
    needs: run-tests
    runs-on: ubuntu-latest
    name: Publish Allure Report to GitHub Pages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Allure Report
        uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
