name: Run API Tests with Allure

on:
  workflow_dispatch:  

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-allure-adaptor allure-pytest

      - name: Install Allure CLI
        run: |
          mkdir -p /tmp/allure
          curl -Lo /tmp/allure/allure.zip https://github.com/allure-framework/allure2/releases/download/2.27.2/allure-2.27.2.zip
          unzip /tmp/allure/allure.zip -d /tmp/allure/
          sudo ln -s /tmp/allure/allure-2.27.2/bin/allure /usr/local/bin/allure
          allure --version

      - name: Run pytest with Allure
        run: |
          mkdir -p allure-results
          pytest tests/ --alluredir=allure-results --clean-alluredir -v

      - name: Generate Allure Report
        run: |
          allure generate allure-results --clean -o allure-report
          echo "Allure report generated in ./allure-report"
