name: Python Tests with Allure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install allure-pytest

    - name: Run tests with pytest and allure
      run: |
        mkdir -p allure-results
        pytest tests/ --alluredir=allure-results --maxfail=1 --disable-warnings -v

    - name: Generate Allure report
      run: |
        allure generate allure-results --clean -o allure-report

    - name: Upload Allure report artifact
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: allure-report
